### ISSUE TITLE
Cannot use reference

### ISSUE THREAD

**Issue by stef-pellegrino** [3F/DllExport#184] opened 2021-02-11 00:23 UTC
Steps to reproduce:

Create C# DLL within a folder TestDll
```
[DllExport]
public int test() {
  return 0;
}
```

- Open VS2019 and Test solution
- Put"DllExport.bat" in same directory than Test.sln
- Double click on DllExport.bat
- Select [Apply]
- Focus on VS + reload all
rebuild gives me :
**error CS0246: The type or namespace name 'DllExport' could not be found (are you missing a using directive or an assembly reference?)**

Click on reference gives me "The proejct cannot be viewed in the object browser because it is not available or not yet build" !??

* `DllExport -version`: 1.7.4
* Used Visual Studio / MSBuild / VS 2019 (Windows 10)

**Comment by 3F** [comment] 2021-02-11 11:38
@stef-pellegrino Please copy everything from the `Data` tab

**Comment by zuoyi1025** [comment] 2021-02-26 12:06
Same Problem here...has anyone any hint?

**Comment by 3F** [comment] 2021-02-26 13:40
@zuoyi1025 
Please follow the issue template to provide a minimal case info. Log or demo project is better in a quick inspections. But I didn't even see the requested info from the Data tab

**Comment by leculver** [comment] 2021-04-19 19:33
Same problem.  The issue seems to be that `RichCodeNav.EnvVarDump` is missing?  Here's what the package manager output looks like when attempting to add the "DllExport" nuget package:

```
  GET https://api.nuget.org/v3-flatcontainer/richcodenav.envvardump/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/richcodenav.envvardump/index.json 129ms
NU1101: Unable to find package RichCodeNav.EnvVarDump. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Package restore failed. Rolling back package changes for 'TestPlugin'.
Time Elapsed: 00:00:00.4875334
```

**Comment by T35R6braPwgDJKq** [comment] 2021-12-17 14:52
```
Installed: True; 1.7.4+c1cc52f; invoked: 1.7.4
Project type: Cs
Storage: ProjectFiles
Compiler.Platform: Auto
Compiler.ordinalsBase: 1
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
Compiler.genExpLib: False
Compiler.peCheck: PeIl
Compiler.patches: None
PreProc.Type: None
PreProc.Cmd: 
PostProc.Type: None
PostProc.ProcEnv: $(SolutionPath);$(MSBuildThisFileFullPath)
PostProc.Cmd: 
SignAssembly: 
Identifier: FEDE8CF5-44B7-41A2-88A4-2D50ED26DE2C
Instance: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MSBuild.exe
Project path: C:\Users\test\source\repos\testdll\testdll\testdll.csproj
Action: Configure
PlatformTarget: AnyCPU
TargetFramework: 
TargetFrameworks: 
TargetFrameworkVersion: v4.5
RootNamespace: testdll
AssemblyName: testdll
MgrArgs: 
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: testdll
ddNS max buffer: 500
UseCecil: True
intermediateFiles: False
timeout: 30000
Options: None
RootPath: C:\Users\test\source\repos\testdll\
PkgPath: C:\Users\test\source\repos\testdll\packages\\DllExport.1.7.4\
SlnFile: 
SlnDir: C:\Users\test\source\repos\testdll\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: 
```

**Comment by 3F** [comment] 2021-12-17 15:30
@T35R6braPwgDJKq 
Please attach at least the **log** when configuring and/or build log with *diagnostic* level to inspect the current problem.

> C:\Users\test\source\repos\testdll\testdll\testdll.csproj

Attach everything if this is a really empty test project for better help to reproduce the problem locally.
Thanks.

**Comment by Miedziaq** [comment] 2021-12-21 09:25
Hi in connecting to our other thread, I prepared some logs.
You should get it from wetransfer.com  to x-3f@outlook.com

**Comment by 3F** [comment] 2021-12-21 14:47
> I prepared some logs.

@Miedziaq There is no `MSB3245: Could not resolve this reference` as you mentioned in https://github.com/3F/DllExport/issues/196#issuecomment-998064774

At least this is what I see in your build log. 

There is single `Error : Invalid Option: /PVP` but this is absolutely another problem. Rather because of your mixed incorrect things in .csproj as I said [earlier](https://github.com/3F/DllExport/issues/196#issuecomment-998004502), for example, due to:

```xml
<TargetExt>.pvp</TargetExt>
```
```xml
<Target Name="PublishPVP" AfterTargets="RGieseckeDllExport" Condition="Exists($(PdfXEditorPluginDir))">
  <Message Text="=== Publish PVP ... ====================================================" />
  <CreateItem Include="$(OutputPath)$(AssemblyName)$(TargetExt)">
    <Output TaskParameter="Include" ItemName="PvpFilesToCopy" />
  </CreateItem>
  <!--<Copy SourceFiles="@(PvpFilesToCopy)" DestinationFolder="$(PdfXEditorPluginDir)" />-->
  <Message Text="=== Publish PVP ... done ===============================================" />
</Target>
```

In any case we support **only** .DLL and .EXE modules. Just consider using our Pre/Post-processing if you need some actions/packing/etc:

* https://github.com/3F/DllExport/wiki/PreProc
* https://github.com/3F/DllExport/wiki/PostProc

**To all,**

Guys! I cannot personally resolve the unknown issues until I receive the minimal info requested earlier. Please also don't fragment information because this could aggregate various unrelated issues between the different stages as you can see above. Also do not distort info as much as possible (please only remove any confidential data).

**Comment by 3F** [comment] 2024-11-24 23:23
If I understood (for all that) the problem correctly,

> error CS0246: The type or namespace name 'DllExport' could not be found (are you missing a using directive or an assembly reference?

For some cases we need to regenerate missed meta. This can be done manually using the following command:

> DllExport -action Restore

If so, 7ee50d032837542c8fca1363d8971f6d9ab0e357 will fix the current problem. You can check it using [related CI build](https://ci.appveyor.com/project/3Fs/dllexport-ix27o/branch/master/artifacts) until the new version.

I close the issue. If the fix doesn't help, please open it again or create a new one.

**Closed by 3F** 2024-11-24 23:23 UTC
Labels: bug, need info
