### ISSUE TITLE
External references/packages are incorrectly included in to the compiled DLL

### ISSUE THREAD

**Issue by Jesse-Schokker** [3F/DllExport#154] opened 2020-05-31 12:30 UTC
Hey,

I am using DllExport for this project and I need a library (Newtonsoft.Json) that serialized JSON for me. As usual, I install it using NuGet. However, when using it inside my Java projects it crashes due to it not being able to find the dependency. As a double check I created another .NET project and simply just referenced the built DLL from there and got the same result. Whenever I use the DLL that is not generated by DllExport it works fine. Only the DLL built using DllExport has this issue.

I've checked the DLL that was generated using a dependency inspector tool ( https://github.com/lucasg/Dependencies ) and it seems like the dependency is registered however it is not found as you can see here:

![](https://i.gyazo.com/5c3ea360e04caa83194d71cdfe4ee96b.png)

I have attached the build log and full project.

Steps to reproduce:

* `DllExport -version`: 1.7.1
* Used Visual Studio / MSBuild / : Visual Studio 2019 / Jetbrains Rider 2020.1

Information from *`Data`* tab or log data: 

[build_new.txt](https://github.com/3F/DllExport/files/4707681/build_new.txt)

Demo Project files / Samples / etc.:

[GDBridgeProject.zip](https://github.com/3F/DllExport/files/4707679/GDBridgeProject.zip)

**Comment by 3F** [comment] 2020-05-31 17:37
Thanks for the updated information. I will continue our discussion from twitter here.

### For the problem with DependenciesLib

This looks similar to #136 where problem is also due to the used third-party tool.

I've quickly inspected mentioned tool and this is it:

https://github.com/lucasg/Dependencies/blob/eb144c9b91561fb84a456d43ba2d5b9942c18aaf/DependenciesLib/FindPeModule.cs#L87

```csharp
((TestPe.LoadSuccessful) && (TestPe.GetProcessor() == ProcessorArch))
.............................^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

For the case with `Newtonsoft.Json.dll` it will return different arch because it was written for 80386 (anycpu for this case regarding CLR) while parent modified module may point to other (see ResolveModule(PE RootPe,... ).

Therefore, you may also note the correct resolving for x86 but not for x64.

Also noticed they used value from offset 0x84, not from offset 0x98 (it could be more clear for resolving in CLR context).

Anyway, you need to report there because this is not related to .NET DllExport.

### For the problem with Java

> when using it inside my Java projects it crashes due to it not being able to find the dependency.

Again, make sure that all dependencies are accessible to load with correct architecture. But seems like this is duplicate of #101

AssemblyResolve is one of the possible solutions. You can also try [Pre-processing](https://github.com/3F/DllExport/wiki/PreProc) same as for Conari.

**Comment by 3F** [comment] 2024-12-17 18:38
I'm closing the issue due to inactivity,
You need to contact lucasg/Dependencies in order to fix his project using the information from my comment above.

Let me also know if solution with AssemblyResolve and/or Pre-processing may not help in some cases.

**Closed by 3F** 2024-12-17 18:38 UTC
Labels: question
