### ISSUE TITLE
DLL is not getting unloaded in MQL language

### ISSUE THREAD

**Issue by woldemar89** [3F/DllExport#207] opened 2022-03-13 16:54 UTC
Hello,

I have an issue with DLL unload in MQL5 language (MetaTrader 5) and
found a comment on MQL forum that describes issue very well:
https://www.mql5.com/en/forum/70621#comment_2200926

In brief following the comment: 
Looks C# DLL created with [DllExport] is not getting correctly unloaded after script execution has been finished, you can unload this only by closing Metatrader application.
Probably because DllMain call with DLL_PROCESS_DETACH made by Metatrader engine is ignored.

I have also attached a screenshot that describes how I found this issue.
![img-2022-03-13-22-34-54](https://user-images.githubusercontent.com/20968707/158070198-87f58149-8693-44a1-82dc-3f3196a0afb7.png)

**Comment by 3F** [comment] 2022-03-13 21:11
Hello,

This is duplicate of #118

**Closed by 3F** 2022-03-13 21:11 UTC
Labels: duplicate, question
