### ISSUE TITLE
Question in case of using DllExport

### ISSUE THREAD

**Issue by cqro** [3F/DllExport#165] opened 2020-06-26 09:11 UTC
Create a module for [OBStudio](https://obsproject.com/) , [obs](https://obsproject.com/) can load with OurILAsm+SysObjRebase setting dll
But when I create new thread or try catch , the obs will throw exception in call `obs_module_load`

![obs](https://user-images.githubusercontent.com/67460060/85842035-94293d80-b7d1-11ea-949e-49fde2469a44.jpg)

```cs
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern int MessageBox(int hWnd, String text, String caption, uint type);

[DllExport(ExportName = "obs_module_load")]
public static bool Load()
{
   MessageBox(0, "Load", "obs_module_load", 0);
   //Task.Factory.StartNew(() =>{});
   //try { MessageBox(0, "Load", "obs_module_load", 0); } catch(Exception ex) { Debug.WriteLine(ex.Message); }
   return true;
}
```
Repo: [obstest](https://github.com/cqro/obstest)  
[Module_Doc](https://obsproject.com/docs/reference-modules.html#module-exports)
For testing:  after build and installed obs , put the dll into obs-studio\obs-plugins\64bit\obstest.dll

**Comment by 3F** [comment] 2020-06-26 11:34
Since your target is Preview .NET 5,
it could be a duplicate of #132. Please follow instructions there.

Let me know the result for .NET Standard 2.0 or .NET Core 2.2

**Comment by cqro** [comment] 2020-06-30 02:33
Thanks, the test results is shown below.

X64 + OurILAsm + SysObjRebase
------------
|Target Framework|TFM| 
|---	|---	| 
|  .NET Standard| <table><tbody><tr><td>✔️</td><td>1.1</td></tr><tr><td>✔️</td><td>1.2</td></tr><tr><td>✔️</td><td>1.3</td></tr><tr><td>✔️</td><td>1.4</td></tr><tr><td>✔️</td><td>1.5</td></tr><tr><td>✔️</td><td>1.6</td></tr><tr><td>✔️</td><td>2.0</td></tr><tr><td>❌</td><td>2.1</td></tr></tbody></table> | 
|  .NET Core| <table><tbody><tr><td>❌</td><td>1.0</td></tr><tr><td>❌</td><td>1.1</td></tr><tr><td>❌</td><td>2.0</td></tr><tr><td>❌</td><td>2.1</td></tr><tr><td>❌</td><td>3.0</td></tr><tr><td>❌</td><td>3.1</td></tr></tbody></table> |

**Comment by 3F** [comment] 2020-06-30 17:27
Thanks for the information. I've checked the issue. This is duplicate of #132 but OBS case looks more problematic because, for example, *"[**netcoreapp2.2** seems pretty fine](https://github.com/3F/DllExport/issues/136#issuecomment-590135715)"*

Temporarily please use netstandard targeting in your case.

**Closed** 2020-06-30 17:27 UTC
Labels: question
