### ISSUE TITLE
Unmanagedexports for .net framework 4.8

### ISSUE THREAD

**Issue by Pratikkulkarni-93** [3F/DllExport#194] opened 2021-09-07 08:36 UTC
Hello. @3F 

I m using the UnmanagedExports 1.2.7 Nuget package and it works for me in framework 4.7 but if I upgrade my framework version to 4.8 I m getting a error with version48 in the UnmanagedExports.

Error msg :
The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version48' was not found.

Thanks for reading!

**Comment by 3F** [comment] 2021-09-07 10:34
Duplicate of #162

@Pratikkulkarni-93 You can easily upgrade to modern DllExport packages. [Start here](https://github.com/3F/DllExport/wiki/Quick-start)

**Closed by 3F** 2021-09-07 10:34 UTC
Labels: question

**Comment by Pratikkulkarni-93** [comment] 2021-09-09 15:16
Hi Denis
I followed the above link and replaced unmanagedexports.
Dllexport 1.7.4 exported  fine , but functionally not working

Could you guide me  more

**Comment by 3F** [comment] 2021-09-09 20:42
@Pratikkulkarni-93 

Hi,
Could you please follow the [bug issue template](https://github.com/3F/DllExport/issues/new?assignees=&labels=bug&template=bug_report.md)? I need logs, configuration, and steps to reproduce.

> I followed the above link and replaced unmanagedexports.
> Dllexport 1.7.4 exported  fine , but functionally not working

Please open a new issue if the problem is different from the current. Also please [make sure](https://github.com/3F/DllExport/issues?q=is%3Aissue) this is not a duplicate.

Thanks.
