### ISSUE TITLE
RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe

### ISSUE THREAD

**Issue by sperazza** [3F/DllExport#103] opened 2019-06-01 14:46 UTC
### How to reproduce
complile a program with following settings:
... 
    
#### Version, configuration, commands:

Versions: 

* `-version`: UnmanagedExports.1.2.7
* `-build-info`:  target x64 or x86, allow unsafe code: True

* Full command: Build
* Environment ( VS, MSBuild, ...): 
VS

Configuration:
TargetFramework .Net 4.5

...

#### Project files, samples:

standard usage, no problem with code, just error message showing on build.

### log

...

Tried reinstalling VS 2017 and UnmanagedExports, still getting same error message on build.

..packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.

-----------

```

**Comment by 3F** [comment] 2019-06-01 15:08
duplicate of #95

**Closed by 3F** 2019-06-01 15:08 UTC
Labels: duplicate, invalid
