### ISSUE TITLE
Unload .net dll of c++ program

### ISSUE THREAD

**Issue by Letomaniy** [3F/DllExport#157] opened 2020-06-02 01:17 UTC
Hello, there is one problem, loading .NET Dll into my program:

![Screenshot_1](https://user-images.githubusercontent.com/61186211/83469254-db006d80-a487-11ea-800a-18f8c6a5e3b4.png)

According to the code presented above, everything is loaded. All dll functions are performed correctly, but after FreeLibrary it is not unloaded (I tried to set a million instead of a triple in a loop, all the same). If you look in Process Hacker 2, we will see that the Dll is loaded twice, photo:

![user619563_pic7140_1590367049](https://user-images.githubusercontent.com/61186211/83469276-ea7fb680-a487-11ea-8ff6-3e2e769ca4d3.png)

I no longer catch up with what to do, and tried to call GetModuleHandle and unload it, but it returns 0. Thanks in advance. In Process Hacker 2, an unloaded dll is marked as "Relocated DLL"

**Comment by 3F** [comment] 2020-06-02 11:50
duplicate of #118

**Closed by 3F** 2020-06-02 11:50 UTC
Labels: question
