### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by chuxiaaaa** [3F/DllExport#218] opened 2023-02-07 11:35 UTC
Error:
RunIlAsm: Something went wrong. We can't find '1' exports from PE32/PE32+ module 'C:\Users\Administrator\source\repos\OAZCSharpSdk\OAZCSharpSdk\bin\Debug\OAZCSharpSdk.dll': AppInfo

```
    public static class Exports
    {
        private static OAZPlugin plugin { get; set; }

        [DllExport]
        public static string AppInfo()
        {
            plugin = Program.Main(null);
            var appObj = new
            {
                name = plugin.Name,
                author = plugin.Author,
                description = plugin.Description,
                version = plugin.Version,
                skey = plugin.Skey,
                sdk = plugin.Sdk,
            };
            return appObj.JsonSerialize();
        }
    }
```

**Comment by 3F** [comment] 2023-02-13 13:08
Hello,

Please follow the issue template.
This is duplicate of #211

The error only means that the automatic check control is triggered on 
your final pe-module.
But you didn't provide anything about it, same to #211

**Closed** 2024-06-05 12:31 UTC
Labels: duplicate
