### ISSUE TITLE
Still not getting a .lib

### ISSUE THREAD

**Issue by jpc2** [3F/DllExport#44] opened 2017-07-23 23:23 UTC
**Edit**:  Never mind....   I found it.  Now to see if I can get FORTRAN to talk to to.

Trying to get a C# project set up so I can call it from a FORTRAN program. Really!

Tried about everything I could here including installing the 8f75a86 build. Still no .lib file. 
New to VS2017 so it takes a bit to figure out where things are. And last did any thing if VS years ago.

Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Professional
Visual Basic 2017   00369-60000-00001-AA283
Microsoft Visual Basic 2017
Visual C# 2017   00369-60000-00001-AA283
Microsoft Visual C# 2017
Visual C++ 2017   00369-60000-00001-AA283
Microsoft Visual C++ 2017

**Comment by jpc2** [comment] 2017-07-26 03:57
Well it worked for a bit. Then I changed something and now it doesn't. The lib.exe problem is due to not having the correct path - I know that much. I may have manually patched it before. 

Unloaded the 8f75a86 build and reloaded it. Here is the config.
![dllexport_config](https://user-images.githubusercontent.com/3154559/28603625-81fe7b72-7182-11e7-96b8-5aba607f245a.PNG)

Builds are set for 'Any CPU', When I build I get this error.
Severity	Code	Description	Project	File	Line	Suppression State
Error		error : Failed to define security permission set for 0x20000001	VistaTGDReader	C:\TTCI_Work\Vista_TGD_dev\VistaTGDReader\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets	47	

I stopped VisualStudio and restarted after the install of DllExport. 
Besides the error above, lib.exe is not being found. 

Here is the diagnostic build output. Maybe it will help. 
[build_log.txt](https://github.com/3F/DllExport/files/1175403/build_log.txt)

**Comment by 3F** [comment] 2017-07-26 12:12
The **0x20000001** is known problem https://github.com/3F/DllExport/issues/19#issuecomment-269245014
Uncheck `Use our IL Assembler` option (msbuild property `DllExportOurILAsm` = `false`) **if** you're using **SecurityPermission** in your assembly.

About lib.exe it's strange because I see paths to VsDevCmd & vcvarsall from your log:

```
1>Set Property: DllExportVsDevCmd=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat
1>Set Property: DllExportVcVarsAll=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\vcvarsall.bat;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat
```

it's required by new env VS2017 to get final path like `<installationPath>\<Version>\<Edition>\VC\Tools\MSVC\<Version>\bin\<HostTarget>\<Arch>` - #37


**Please also note**, the message `Cannot find lib.exe in '...'` irrelevant after 8f75a86 because now it just means that we can't find it through obsolete method :) I forget about this msg, so I'll change it later.

So, what we to do... I can prepare later special build with markers to isolate your problem because it's not reproduced for me. 

> Then I changed something and now it doesn't. 

It would be great to remember something :)

But if you already have [configured](https://github.com/3F/DllExport#how-to-debug) debug of our project, you can check this place: https://github.com/3F/DllExport/blob/8f75a868e4ae688ebac5f34a245857cc287fde9b/RGiesecke.DllExport/Parsing/ILAsm.cs#L181

**Comment by jpc2** [comment] 2017-07-26 13:44
@3F  Thanks for the reply.  
It was the ILAsm setting. I have not specifically set **SecurityPermissions** . And for this don't need them set. Just trying to build a simple data file reader dll for files with an XML header. Any clue on where it is being set? 

I unloaded and reloaded the DllExport package and it works again. Both x64 and X86 have the .dll and .lib files now.

**Comment by 3F** [comment] 2017-07-26 14:42
@jpc2 

Did you try with `DllExportOurILAsm = false` ?

Can you also give some trivial sample of demo project etc. to reproduce your case with 0x20000001 ? because it should be exactly here - https://github.com/3F/coreclr/blob/master/src/ilasm/assembler.cpp#L2263

> I unloaded and reloaded the DllExport package and it works again. Both x64 and X86 have the .dll and .lib files now.

That is, you can't reproduce this anymore ? or it still after some time ?

**Comment by 3F** [comment] 2017-08-20 11:43
@jpc2 I need details, Please also check it with latest v1.6 **beta2** release:

* Latest manager: https://3F.github.io/DllExport/releases/latest/manager/
* Please note again - you shouldn't use standard nuget clients anymore: https://www.youtube.com/watch?v=okPThdWDZMM

**Comment by 3F** [comment] 2017-10-27 21:36
I closed this, because I can't reproduce this problem and still have no any new details about this.

Reopen if it's reproduced for [v1.6-beta3+](https://3f.github.io/DllExport/releases/latest/manager/) releases (together with detailed log).

**Please also note**: For Visual Studio 15' you should use MSBuild v15+ because the old versions can't populate all required properties because of new API. For example, v14.0.25420.1 may cause this error for VS2017 projects:

```
lib tool via LibToolDllPath: -1
Export warning EXP0014: RunIlAsm: An error occurred while calling lib.exe: ...
```
etc.

For this case I recommend to use - [hMSBuild](https://github.com/3F/hMSBuild)

**Closed by 3F** 2017-10-27 21:36 UTC
Labels: bug

**Comment by 3F** [comment] 2017-12-29 21:42
*How to avoid EXP0014: RunIlAsm. The library manager still cannot be found.:*
* [This screencast](https://www.youtube.com/watch?v=zUejJ4vUPGw) illustrates my solution above - https://github.com/3F/DllExport/issues/44#issuecomment-340095777
