### ISSUE TITLE
DllExport_Configure.bat crashes

### ISSUE THREAD

**Issue by ArgusMagnus** [3F/DllExport#58] opened 2017-11-22 12:28 UTC
If I try to build the project with the NuGet package installed, the message telling me that nuget is no longer support keeps poping up and nothing else happens if I close it. If I run the DllExport_Configure.bat manually, I get the following error, which I guess is because I have other project types in the same solution which are not supported (Apra.Core is a .NETStandard project, I want to use DllExport with Apra.PointOfService which is a .NET 4.6.1 library):

> D:\Projekte\Apra>DllExport -action Configure
> [1:14:05 PM.2277] [Info] Action: Configure; Storage: Default
> [1:14:05 PM.2656] [Debug] listener has been added into container - e068644b-0ba2-3068-bb75-78a38126396f
> [1:14:05 PM.2666] [Debug] listener has been added into container - 30d0f9bf-bd74-362b-9041-98e50cae8425
> [1:14:05 PM.2676] [Debug] listener has been added into container - 7dff6713-85cc-3710-9b8b-8b4240a43130
> [1:14:05 PM.2676] [Debug] listener has been added into container - 05681662-92bd-34b1-9ff2-1736ba176220
> [1:14:05 PM.2676] [Debug] listener has been added into container - a1ad418f-97ee-335c-944b-f8f9b730be84
> [1:14:05 PM.2676] [Debug] listener has been added into container - 97a64ce1-bcce-374c-bbfe-8d10b798227b
> [1:14:05 PM.2966] [Trace] ProjectItem ->['{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}'; 'Apra.Core'; 'Apra.Core\Apra.Core.csproj'; 'D:\Projekte\Apra\Apra.Core\Apra.Core.csproj'; '{9A19103F-16F7-4668-BE54-9A1E7A4F7556}' ]
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{D84B7C9C-DBB9-4BED-9888-66A6E1214580}'; 'Apra.Networking'; 'Apra.Networking\Apra.Networking.csproj'; 'D:\Projekte\Apra\Apra.Networking\Apra.Networking.csproj'; '{9A19103F-16F7-4668-BE54-9A1E7A4F7556}' ]
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{2B954A3B-B004-4680-9731-F3E35C7B2573}'; 'SolutionFiles'; 'SolutionFiles'; 'D:\Projekte\Apra\SolutionFiles'; '{2150E333-8FDC-42A3-9474-1A3956D46DE8}' ]
> [1:14:05 PM.2996] [Debug] SolutionFiles has been ignored as solution-folder :: 'Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "SolutionFiles", "SolutionFiles", "{2B954A3B-B004-4680-9731-F3E35C7B2573}"'
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}'; 'Apra.Test'; 'Apra.Test\Apra.Test.csproj'; 'D:\Projekte\Apra\Apra.Test\Apra.Test.csproj'; '{9A19103F-16F7-4668-BE54-9A1E7A4F7556}' ]
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{47A7F790-5BDE-498E-8799-409291A4AE76}'; 'Apra.PointOfService'; 'Apra.PointOfService\Apra.PointOfService.csproj'; 'D:\Projekte\Apra\Apra.PointOfService\Apra.PointOfService.csproj'; '{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}' ]
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{E6438782-B2CC-4B2A-B759-C8DE99651EDF}'; 'Apra.PointOfService.Cpp'; 'Apra.PointOfService.Cpp\Apra.PointOfService.Cpp.vcxproj'; 'D:\Projekte\Apra\Apra.PointOfService.Cpp\Apra.PointOfService.Cpp.vcxproj'; '{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}' ]
> [1:14:05 PM.2996] [Trace] ProjectItem ->['{F232C615-C8FA-49E2-943B-E7F4A0C6109F}'; 'Apra.TestCpp'; 'Apra.TestCpp\Apra.TestCpp.vcxproj'; 'D:\Projekte\Apra\Apra.TestCpp\Apra.TestCpp.vcxproj'; '{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}' ]
> [1:14:05 PM.3016] [Info] Solution Configuration ->['Debug' ; 'Any CPU']
> [1:14:05 PM.3016] [Info] Solution Configuration ->['Debug' ; 'x64']
> [1:14:05 PM.3016] [Info] Solution Configuration ->['Debug' ; 'x86']
> [1:14:05 PM.3016] [Info] Solution Configuration ->['Release' ; 'Any CPU']
> [1:14:05 PM.3016] [Info] Solution Configuration ->['Release' ; 'x64']
> [1:14:05 PM.3026] [Info] Solution Configuration ->['Release' ; 'x86']
> [1:14:05 PM.3066] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Debug|Any CPU` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3106] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3106] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Debug|x64` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3106] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3106] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Debug|x86` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3106] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3106] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Release|Any CPU` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3116] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3116] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Release|x64` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3116] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3126] [Info] New Project Configuration `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`, `Release|x86` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3126] [Debug] Project Configuration, update Build.0  `{69E39843-A9F7-4D7E-A14C-CE206FC88FC7}`
> [1:14:05 PM.3136] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Debug|Any CPU` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3136] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3146] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Debug|x64` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3146] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3156] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Debug|x86` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3156] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3186] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Release|Any CPU` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3196] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3216] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Release|x64` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3216] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3226] [Info] New Project Configuration `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`, `Release|x86` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3226] [Debug] Project Configuration, update Build.0  `{D84B7C9C-DBB9-4BED-9888-66A6E1214580}`
> [1:14:05 PM.3236] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Debug|Any CPU` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3241] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3246] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Debug|x64` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3251] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3256] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Debug|x86` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3261] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3266] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Release|Any CPU` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3291] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3296] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Release|x64` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3311] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3316] [Info] New Project Configuration `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`, `Release|x86` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3321] [Debug] Project Configuration, update Build.0  `{E4FB19F4-FE2C-4821-A5C1-A3497E00B43B}`
> [1:14:05 PM.3326] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Debug|Any CPU` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3331] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3336] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Debug|x64` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3341] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3346] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Debug|x86` = `Debug|Any CPU` /ActiveCfg
> [1:14:05 PM.3351] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3356] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Release|Any CPU` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3361] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3366] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Release|x64` = `Release|x64` /ActiveCfg
> [1:14:05 PM.3371] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3391] [Info] New Project Configuration `{47A7F790-5BDE-498E-8799-409291A4AE76}`, `Release|x86` = `Release|Any CPU` /ActiveCfg
> [1:14:05 PM.3391] [Debug] Project Configuration, update Build.0  `{47A7F790-5BDE-498E-8799-409291A4AE76}`
> [1:14:05 PM.3412] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Debug|Any CPU` = `Debug|Win32` /ActiveCfg
> [1:14:05 PM.3412] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Debug|x64` = `Debug|x64` /ActiveCfg
> [1:14:05 PM.3422] [Debug] Project Configuration, update Build.0  `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`
> [1:14:05 PM.3422] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Debug|x86` = `Debug|Win32` /ActiveCfg
> [1:14:05 PM.3432] [Debug] Project Configuration, update Build.0  `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`
> [1:14:05 PM.3432] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Release|Any CPU` = `Release|Win32` /ActiveCfg
> [1:14:05 PM.3442] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Release|x64` = `Release|x64` /ActiveCfg
> [1:14:05 PM.3452] [Debug] Project Configuration, update Build.0  `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`
> [1:14:05 PM.3462] [Info] New Project Configuration `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`, `Release|x86` = `Release|Win32` /ActiveCfg
> [1:14:05 PM.3462] [Debug] Project Configuration, update Build.0  `{E6438782-B2CC-4B2A-B759-C8DE99651EDF}`
> [1:14:05 PM.3472] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Debug|Any CPU` = `Debug|Win32` /ActiveCfg
> [1:14:05 PM.3472] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Debug|x64` = `Debug|x64` /ActiveCfg
> [1:14:05 PM.3502] [Debug] Project Configuration, update Build.0  `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`
> [1:14:05 PM.3502] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Debug|x86` = `Debug|Win32` /ActiveCfg
> [1:14:05 PM.3522] [Debug] Project Configuration, update Build.0  `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`
> [1:14:05 PM.3522] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Release|Any CPU` = `Release|Win32` /ActiveCfg
> [1:14:05 PM.3532] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Release|x64` = `Release|x64` /ActiveCfg
> [1:14:05 PM.3532] [Debug] Project Configuration, update Build.0  `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`
> [1:14:05 PM.3542] [Info] New Project Configuration `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`, `Release|x86` = `Release|Win32` /ActiveCfg
> [1:14:05 PM.3542] [Debug] Project Configuration, update Build.0  `{F232C615-C8FA-49E2-943B-E7F4A0C6109F}`
> [1:14:05 PM.3792] [Info] Load project {69E39843-A9F7-4D7E-A14C-CE206FC88FC7}:Debug|AnyCPU :: 'Apra.Core' ('D:\Projekte\Apra\Apra.Core\Apra.Core.csproj')
> [1:14:05 PM.3862] [Fatal] ERROR-Wizard: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\Projekte\Apra\Apra.Core\Apra.Core.csproj
> [1:14:05 PM.3872] [Warn] SlnDir: 'D:\Projekte\Apra\.\'
> [1:14:05 PM.3872] [Warn] SlnFile: ''
> [1:14:05 PM.3882] [Warn] PkgPath: 'D:\Projekte\Apra\packages\\DllExport.1.6.0-beta3\'
> [1:14:05 PM.3892] [Warn] MetaLib: 'tools\raw\lib\net20\DllExport.dll'
> [1:14:05 PM.3902] [Warn] DxpTarget: 'tools\net.r_eg.DllExport.targets'
> [1:14:05 PM.3922] [Warn] RootPath: 'D:\Projekte\Apra\'
> [1:14:05 PM.3922] [Warn] Storage: 'Default'
> [1:14:05 PM.3932] [Warn] Action: 'Configure'

**Comment by 3F** [comment] 2017-11-22 13:04
duplicate of #56

```
ERROR-Wizard: The default XML namespace of the project must be the MSBuild XML namespace...
```
Please wait public release or use our nightly builds ! Read additional details there.
Related CI build: https://ci.appveyor.com/project/3Fs/dllexport/build/build-71/artifacts


> If I try to build the project with the NuGet package installed, the message telling me that nuget is no longer support keeps poping up and nothing else happens if I close it. 

The message below also tells you about required removing this before continue. Please remove, then continue. Just information for [obsolete way](https://github.com/3F/DllExport#how-to-get-dllexport) because we still use nuget server by default for distribution.

I illustrated this moment here, again: https://youtu.be/okPThdWDZMM?t=10s

**Closed by 3F** 2017-11-22 13:04 UTC

**Comment by ArgusMagnus** [comment] 2017-11-23 08:09
The nightly build crashes with the same error as posted above.

**Comment by 3F** [comment] 2017-11-23 12:10
@ArgusMagnus It cannot be true. I hope you're trying with new binaries from `DllExport_v1.6.0.63089_20eb9db.zip` and of course together with any DllExport.bat that's configured **for this package** instead of beta3 release from nuget server by default.

use key `-build-info` and report about result, it should be:
```

    S_NUM:              1.6.0
    S_REV:              63089
    S_NUM_REV:          1.6.0.63089
    S_REL:              beta3
    bSha1:              20eb9db
    bName:              master
    bRevc:              88
...
```

so you can use for example:

```bat
DllExport -pkg-link https://ci.appveyor.com/api/buildjobs/76c9hywa45buks9b/artifacts/bin\Release\DllExport.1.6.0-beta3.nupkg -packages packages\\ -action Configure
```
call it inside root solution directory

**Comment by ArgusMagnus** [comment] 2017-11-28 06:44
It seems to work now with the 1.6-RC
