### ISSUE TITLE
Configure fails for unknown reason

### ISSUE THREAD

**Issue by abnud1** [3F/DllExport#139] opened 2020-03-25 12:11 UTC
How to reproduce:

... Launch DLLExport.bat in the solution directory
... Choose a .Net standard 2.1 project or .Net core 3.1 project
... Click Apply
... Nothing happens, the project isn't changed and DLLExport isn't found.

* `-version`: v1.7.0.60761+0a002a7
* `-build-info`:

    S_NUM:              1.7.0
    S_REV:              60761
    S_NUM_REV:          1.7.0.60761
    S_REL:
    bSha1:              0a002a7
    bName:              master
    bRevc:              201
    MetaCor:            netstandard1.1
    MetaLib:            v2.0
    Wizard:             v4.0
    Configuration:      PublicRelease
    Platform:           Any CPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534
* Full command to Manager: ./DLLExport.bat
* Project type: .Net standard project or .Net core project
* Environment ( VS, MSBuild, ...): .Net core 3.1, IDE IS Rider 2019.3 not Visual Studio, MSBUILD version is 16

log:
[DotNetCoreProblem.log](https://github.com/3F/DllExport/files/4380735/DotNetCoreProblem.log)

**Comment by 3F** [comment] 2020-03-25 13:50
Thanks for the report,

Is there any reason **why** are you using an *offline* version? Did you try with normal *full* version?

I'm watching problem with incorrect msbuild instance in your environment. Thus, can you first show the result for the following command via [hMSBuild](https://github.com/3F/hMSBuild/releases/download/v2.3/hMSBuild.bat):

```
hMSBuild -debug -only-path
```

And via [vswhere.exe](https://github.com/microsoft/vswhere/releases/download/2.8.4/vswhere.exe)

```
vswhere -requires Microsoft.Component.MSBuild -products *
vswhere -requires Microsoft.Component.MSBuild -products * -latest
```

**Comment by abnud1** [comment] 2020-03-25 16:19
@3F I used the offline version because the Online version for some reason shows these two strange messages:

> 
> [6:07:18 PM.6325] [Debug] Get data: https://3f.github.io/DllExport/data/pkgrel
> [6:07:19 PM.0276] [Debug] Rcv failed: Request aborted, failed to create safe SSL/TLS context.

But probably those messages aren't related.
`hMSBuild -debug -only-path` output:

> 
> [18:14:58.44 ] trying via vswhere...
> [18:14:58.45 ] bat/exe:  C:\Users\Administrator\Desktop\Workflow\Devices\vswhere
> [18:14:58.46 ] bat/exe:  C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere
> [18:14:58.46 ] vswbin:  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
> [18:14:58.47 ] assign command:  -products * -latest
> [18:14:58.47 ] attempts with filter:
> [18:14:58.56 ] attempts with filter:   -prerelease
> [18:14:58.60 ] Searching from Visual Studio - 2015, 2013, ...
> [18:14:58.61 ] check 14.0
> [18:14:58.63 ] check 12.0
> [18:14:58.65 ] -vs: not found
> [18:14:58.66 ] Searching from .NET Framework - .NET 4.0, ...
> [18:14:58.66 ] check 4.0
> [18:14:58.69 ] :msbfound  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\\MSBuild.exe
> 
> 
and `vswhere -requires Microsoft.Component.MSBuild -products *` output:

> 
> Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> 
same output for `vswhere -requires Microsoft.Component.MSBuild -products * -latest` command.

**Comment by 3F** [comment] 2020-03-25 17:58
> But probably those messages aren't related.

The first message is related to another issue, thanks for the information!

> vswhere -requires Microsoft.Component.MSBuild -products *

Since vswhere indicates the same result, I think the problem is related rather to the installation API but not to DllExport.

> MSBUILD version is **16**

Can you describe more about installation way (part of what is) and actual paths to the actual tools? What full version of the instance?

Also, can you try with   `-all` flag that will find all instances even if they are **incomplete**, i.e.:

```
vswhere -requires Microsoft.Component.MSBuild -products * -prerelease -all
```
If still nothing, please report here about results with vswhere command above: https://github.com/microsoft/vswhere/issues

**Comment by abnud1** [comment] 2020-03-26 12:21
> Can you describe more about installation way (part of what is) and actual paths to the actual tools? What full version of the instance?

MSBuild is included with dotnet core SDK 3.1 which comes with visual studio 2019 currently installed on my device, visual studio 2019 currently is pending an update.

> Also, can you try with -all flag that will find all instances even if they are incomplete, i.e.:
command output:

> Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> instanceId: cc619792
> installDate: 5/25/2019 11:41:05 AM
> installationName: VisualStudio/16.4.6+29905.134
> installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
> installationVersion: 16.4.29905.134
> productId: Microsoft.VisualStudio.Product.Enterprise
> productPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe
> state: 13
> isComplete: 0
> isLaunchable: 0
> isPrerelease: 0
> isRebootRequired: 0
> displayName: Visual Studio Enterprise 2019
> description: Scalable, end-to-end solution for teams of any size
> channelId: VisualStudio.16.Release
> channelUri: https://aka.ms/vs/16/release/channel
> enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
> installChannelUri: K:\ChannelManifest.json
> releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.4.6
> thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
> updateDate: 2020-03-11T15:24:06.1933991Z
> catalog_buildBranch: d16.4
> catalog_buildVersion: 16.4.29905.134
> catalog_id: VisualStudio/16.4.6+29905.134
> catalog_localBuild: build-lab
> catalog_manifestName: VisualStudio
> catalog_manifestType: installer
> catalog_productDisplayVersion: 16.4.6
> catalog_productLine: Dev16
> catalog_productLineVersion: 2019
> catalog_productMilestone: RTW
> catalog_productMilestoneIsPreRelease: False
> catalog_productName: Visual Studio
> catalog_productPatchVersion: 6
> catalog_productPreReleaseMilestoneSuffix: 1.0
> catalog_productSemanticVersion: 16.4.6+29905.134
> catalog_requiredEngineVersion: 2.4.1111.43337
> properties_campaignId:
> properties_canceled: 1
> properties_channelManifestId: VisualStudio.16.Release/16.4.6+29905.134
> properties_nickname:
> properties_operationMode: 0
> properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

**Comment by abnud1** [comment] 2020-03-26 12:40
I forget to mention the dotnet core SDK path: C:\Program Files\dotnet\sdk\3.1.102
at this path MSBuild.dll exists, not exe but that's the MSBuild Rider uses

**Comment by 3F** [comment] 2020-03-26 13:19
Well, this is it:

> isComplete: 0

I'm not really sure about *incomplete* stage for the products. And I am not ready to support it today.

But anyone else can open PR to consider some additional support with surely tested environment where only incomplete products.

@abnud1 

You need to complete the installation for today and please make sure you have installed *MSBuild component* in addition to mentioned *.NET Core 3.1 SDK:* 

> C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe 

* `Edit` - `Individual components` - Compilers, build tools, and runtimes - **`MSBuild`**

I close the issue due to irrelevant problem for the current project. Feel free to continue for some related purposes.

**Closed by 3F** 2020-03-26 13:19 UTC

**Comment by 3F** [comment] 2020-03-26 13:27
I forgot to say, an additional MSBuild component above is required **only when** you're trying .NET Core based projects and/or modern SDK style.

At least today. Who follows me also should know about future planned changes in this area. Hope for this.
