### ISSUE TITLE
Build process stalled

### ISSUE THREAD

**Issue by pixelaminator** [3F/DllExport#51] opened 2017-09-23 12:30 UTC
I'm making a plugin for CorelDRAW with CorelDRAW API in VB.NET.
I have following code that seems to cause the Build process to stall while using DllExport. I had to kill ildasm/MSBuild process just to cancel the build.

```
Public Function ConvertBitmap(bw As BackgroundWorker) As Integer
        Try
            'Declare Document and Shape Object
            Dim pg As Page
            Dim X As Double
            Dim Y As Double
            Dim w As Double
            Dim h As Double
            Dim sh As Shape

            cdraw.ActiveDocument.BeginCommandGroup("Convert ke Bitmap")

            For Each pg In cdraw.ActiveDocument.Pages
                PageNumber += 1

                pg.Activate()
                pg.GetBoundingBox(X, Y, w, h)

                '----------- I suspect the cause was the two lines of code below: ---------------
                sh = pg.SelectShapesFromRectangle(X, Y + h, X + w, Y, False)
                sh.ConvertToBitmapEx(cdrImageType.cdrCMYKColorImage, True, True, 300, cdrAntiAliasingType.cdrNormalAntiAliasing, True, True)

                bw.ReportProgress(CInt((PageNumber / PageNumberMax) * 100))
            Next pg
            cdraw.ActiveDocument.EndCommandGroup()
            Return 1 'Success
            Exit Function
        Catch ex As System.Exception
            cdraw.ActiveDocument.EndCommandGroup()
            Return 0 'Failed
            Exit Function
        End Try
    End Function
```
Commenting out the code would make the Build succeed. 
I'm using latest pre-release beta of DLLExport in VS2017. Any help will be appreciated.

**Comment by 3F** [comment] 2017-09-24 10:31
1. try to provide build log via msbuild, I will look into in details later:
```
msbuild <sln> /t:Rebuild /m:4 /v:diag
```
2. It shouldn't affect for build process, but anyway, only primitive types and pointer-based types instead of BackgroundWorker etc. Read here:  https://github.com/3F/DllExport/issues/created_by/K-Full
3. What about `our IL Assembler` option ? Try to check this with several ildasm version anyway.

**Comment by pixelaminator** [comment] 2017-09-25 02:01
Hello, here's the log file: 
https://gist.githubusercontent.com/pixelaminator/f696d2716dc18e7733e580524ed93799/raw/67e57690f3c49ab43f693d0e115e54dac1c6c86e/MSBuild.log

I've tried to use "our IL Assembler" option but no changes at all

**Comment by 3F** [comment] 2017-09-25 15:36
> What's your best suggestions to workaround this?

How I can know what you do at all :)

Can you also show the same log but with disabled our assembler - DllExportOurILAsm = false

I see that IL code has been successfully generated by ildasm

```csharp
.method public static void modopt(['mscorlib']'System.Runtime.CompilerServices.CallConvCdecl')  'CG_Publish'() 
// should be exported as `CGPublish` #1
```

```csharp
.method public static void modopt(['mscorlib']'System.Runtime.CompilerServices.CallConvCdecl')  'CG_TestSaving'()
// should be exported as `CGTestSaving` #2
```

therefore the problem should be with re-assembling new IL code, so we need to look incorrect **instructions for new assembly**, or any other problems with ilasm (in log, I see only list of assembled methods and stack trace from our tool to point of ilasm execution).

You can inspect new code manually to find this error. To compile it from IL:  

ilasm /out:CG_FileManagement.dll CG_FileManagement.x86.il /DLL /resource=CG_FileManagement.res /debug 

use /CVRES="C:\Windows\Microsoft.NET\Framework\v4.0.30319" if you will do it through our assembler.

Or, try to send anything for debug, but do not forget about copyrights, license etc. of your (or company) program, because this code will be available for 3rd party side, do not forget about this. 

You can also try to prepare basic test program to reproduce this bug if you can't send original dll/il or can't inspect it manually.

And also try with any struct-wrapper to aggregate additional state from unmanaged side, i.e. over BackgroundWorker.
Some of this I already described for other user, again [here](https://github.com/3F/DllExport/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20author%3AK-Full%20created%3A%3C2017-04-01%20) or try to look some wrapper from [Conari](https://github.com/3F/Conari) project.

**Comment by pixelaminator** [comment] 2017-09-27 04:19
My whole project is available on Github, you can review it:
https://github.com/pixelaminator/CG_Tools/tree/publish-cg-digital/CG_FileManagement
The file with problematic code is in this file:
https://github.com/pixelaminator/CG_Tools/blob/publish-cg-digital/CG_FileManagement/CG_PublishDigital/ClsCDraw.vb

I've tried to run ILasm with your command but the result is kind of incomprehensible (the cmd window truncates the debug log).

**Comment by 3F** [comment] 2017-09-27 11:53
well, I need this for build your src:

```xml
<Reference Include="Corel.Interop.VGCore, Version=17.6.0.1021, Culture=neutral, PublicKeyToken=e4835428e22ad6f9, processorArchitecture=MSIL" Condition="'$(Configuration)'=='X7'">
  <HintPath>C:\Program Files\Corel\CorelDRAW Graphics Suite X7\Programs64\Assemblies\Corel.Interop.VGCore.dll</HintPath>
  <SpecificVersion>False</SpecificVersion>
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
<Reference Include="Corel.Interop.VGCore, Version=18.1.0.661, Culture=neutral, PublicKeyToken=e4835428e22ad6f9, processorArchitecture=MSIL" Condition="'$(Configuration)'=='X8'">
  <HintPath>C:\Program Files\Corel\CorelDRAW Graphics Suite X8\Programs64\Assemblies\Corel.Interop.VGCore.dll</HintPath>
  <SpecificVersion>False</SpecificVersion>
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
<Reference Include="Corel.Interop.VGCore, Version=19.1.0.419, Culture=neutral, PublicKeyToken=e4835428e22ad6f9, processorArchitecture=MSIL" Condition="'$(Configuration)'=='2017'">
  <HintPath>C:\Program Files\Corel\CorelDRAW Graphics Suite 2017\Programs64\Assemblies\Corel.Interop.VGCore.dll</HintPath>
  <SpecificVersion>False</SpecificVersion>
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
```    
`Corel.Interop.VGCore.dll` is distributed only with **CorelDRAW Graphics Suite** or I can get it separately like SDK etc. ? just for build, where to find ?


Also, I see this - `UnmanagedExports.1.2.7`

```xml
<Reference Include="RGiesecke.DllExport.Metadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8f52d83c1a22df51, processorArchitecture=MSIL">
  <HintPath>..\packages\UnmanagedExports.1.2.7\lib\net\RGiesecke.DllExport.Metadata.dll</HintPath>
  <Private>False</Private>
</Reference>
```

so, did you try with our package o_O ? https://www.nuget.org/packages/DllExport/

> the cmd window truncates the debug log

```
command_above > build.log
```
or `Properties` - `Layout` - `Screen Buffer Size` - `height ` change to max value 9999

**Comment by pixelaminator** [comment] 2017-09-28 02:49
Oh right, sorry I forgot about those 3rd party references. They're only available if you install CorelDRAW Graphics Suite X7.

Here is the DLL file without exports.
[CG_FileManagement.zip](https://github.com/3F/DllExport/files/1339329/CG_FileManagement.zip)

**Comment by 3F** [comment] 2017-09-28 12:37
I have no see any problems :)

It successfully injected as:

```
00000001    00012FFE    0000    00014044    CGPublish
00000002    0001300E    0001    0001404E    CGTestSaving
```

the is modified module:
[CG_FileManagement_mod.zip](https://github.com/3F/DllExport/files/1340819/CG_FileManagement_mod.zip)

So I don't know exactly without CorelDRAW Graphics Suite.

Try to disable embedding Corel.Interop.VGCore.dll:

```xml
<EmbedInteropTypes>False</EmbedInteropTypes>
```

**Comment by pixelaminator** [comment] 2017-09-29 04:31
Ah, you are right...turns out I have to disable interop embedding to make it compile with DLLExport.
Now I had to get around my code to make it work with the new change.. or keep old code but doing it manually as you did.

Thanks for the help :+1:

**Comment by 3F** [comment] 2017-09-29 11:25
Good news :)

I closed this issue because it more like single problem. For example, I also checked other interop type `EnvDTE` (part of VSSDK)

```xml
<Reference Include="envdte, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
<Reference Include="envdte80, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
```

Works fine with both ilasm versions. 

Reopen issue if you will have additional information.

**Closed by 3F** 2017-09-29 11:25 UTC
