### ISSUE TITLE
System.MissingMethodException in C#/EExternalException in Delphi when calling a C# exported function that calls another exported function

### ISSUE THREAD

**Issue by meindratheal** [3F/DllExport#155] opened 2020-06-01 13:09 UTC
Steps to reproduce:

1. Create a new solution with two projects, a Class Library and something runnable (I've used both a console app and a forms application). I'm targeting .NET Framework 4.7.2. Can also reproduce if targeting 4.5.0.
2. Install the NuGet package on the Class Library. When the DllExport configuration pops up, tick the Installed button on the Class Library project, then hit Apply. No other changes needed.
3. Write two exported functions in the Class Library project. Have the second one call the first. So something like this:

```C#
        [DllExport]
        public static void WorksFine()
        {
            //Does nothing.
        }

        [DllExport]
        public static void CausesError()
        {
            WorksFine();
        }
```
4. Call those functions from with C#. Observe that you get System.MissingMethodException when CausesError tries to call WorksFine.
```C#

	static void Main(string[] args)
	{
		Console.WriteLine("Calling WorksFine");
		Exports.WorksFine();
		Console.WriteLine("Calling CausesError");
		Exports.CausesError(); //Throws System.MissingMethodException: 'Method not found: 'Void TheDll.Exports.WorksFine()'.'
		Console.WriteLine("Done");
		Console.ReadKey();
	}
```
In my use case I'm consuming these exports in a Delphi program. Calling WorksFine works fine, calling CausesError generates an EExternalException on the Delphi side, which indicates that an uncaught exception happened in the C# side (which would be the MissingMethodException).
. . .

* `.NET DllExport 1.7.1.6918+61defd6`
* VS2019 v16.5.5, using .NET Framework 4.7.2 for the projects.
Data tab:
```
Installed: True
Project type: Cs
PkgVer: 1.7.1
Storage: ProjectFiles
Compiler.Platform: Auto
Compiler.ordinalsBase: 1
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
Compiler.genExpLib: False
Compiler.peCheck: PeIl
Compiler.patches: None
PreProc.Type: None
PreProc.Cmd: 
PostProc.Type: None
PostProc.ProcEnv: $(SolutionPath);$(MSBuildThisFileFullPath)
PostProc.Cmd: 
SignAssembly: 
Identifier: C038D930-FF6E-498C-B66E-21E3457C5B40
Instance: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe
Project path: C:\Users\redacted\source\repos\DllExportBug\TheDll\TheDll.csproj
Action: Configure
PlatformTarget: x86
TargetFramework: 
TargetFrameworks: 
TargetFrameworkVersion: v4.5
RootNamespace: TheDll
AssemblyName: TheDll
MgrArgs: 
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: TheDll
ddNS max buffer: 500
UseCecil: True
intermediateFiles: False
timeout: 30000
RootPath: C:\Users\redacted\source\repos\DllExportBug\
PkgPath: C:\Users\redacted\source\repos\DllExportBug\packages\\DllExport.1.7.1\
SlnFile: 
SlnDir: C:\Users\redacted\source\repos\DllExportBug\.\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: 
```

Demo Project files / Samples / etc.:

Minimal sample project attached.
[DllExportBug.zip](https://github.com/3F/DllExport/files/4712433/DllExportBug.zip)

**Comment by meindratheal** [comment] 2020-06-01 14:26
Edited title and body to include that this also happens if everything's purely in C#, rather than calling from Delphi.

**Comment by 3F** [comment] 2020-06-01 15:42
@meindratheal Is there any reason why are you avoiding our [bug issue template](https://github.com/3F/DllExport/issues/new?labels=bug&template=bug_report.md) ? Please update information.

It can be a duplicate of #130

**Comment by meindratheal** [comment] 2020-06-01 16:54
That would be because I didn't know that template existed! I've updated to match, and also attached a minimal repro.

**Comment by 3F** [comment] 2020-06-01 18:36
Thanks for the updated information! This is duplicate of https://github.com/3F/DllExport/issues/94#issuecomment-474470670

**Closed by 3F** 2020-06-01 18:36 UTC
