### ISSUE TITLE
Breakpoints not hit from .NET Standard 2.1 DllExport

### ISSUE THREAD

**Issue by pmariso** [3F/DllExport#137] opened 2020-02-12 22:16 UTC
I realize this probably isn't a DllExport issue, but maybe others using it have run into it.

Using the latest version of Visual Studio 2019 Preview.

I have a .NET Standard 2.1 class library that exports several native APIs using [DllExport].  If I attach the debugger to the process that loads the DLL and calls the API, break points set in the class library DO NOT hit.  I have Native Debugging enabled, and also Use Managed Compatibility Mode.  I can confirm the APIs are being called and returning, however, because the native application that uses them is working.

Alternatively, if I build the same class library as a .NET Framework library, and repeat the scenario, the debug breakpoints DO hit.

Is there a problem with Visual Studio debugger transitioning from native to Managed under .Net Core 3.0 / .NET Standard 2.1?  Or am I potentially doing something wrong, or have wrong settings?

I've done lots of searches on this topic and haven't found a good answer yet.

**Comment by 3F** [comment] 2020-02-12 22:57
Because ilasm **on coreclr** will not generate `.line` directives at all:
https://github.com/3F/coreclr/issues/3

I have the plan to review this feature of course (~someday); But my actual modified versions still follows this logic.

Closed as duplicate of #23. Feel free to continue there.

**Closed by 3F** 2020-02-12 22:57 UTC
Labels: question

**Comment by pmariso** [comment] 2020-02-12 23:18
Thank you!
